const express = require('express');
const router = express.Router();
const Authentication = require('../Controllers/Controller');
const Middleware = require('../Controllers/Middleware');
router.post('/api/routes/register', Authentication.register);
router.post('/api/routes/login', Authentication.login);
router.get('/api/routes/Productcart', Middleware.verifyToken, Authentication.ProductCart);
router.delete('/api/routes/delete/:id', Authentication.removeCart);
router.post('/api/routes/cart', Authentication.Cart);
module.exports = router;
